import assert from "node:assert/strict";
import { execSync } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { after, before, test } from "node:test";
import { snapshotSqliteSeedDatabase } from "../test/sqlite-snapshot.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const apiRoot = path.resolve(__dirname, "../../");
const seedDbPath = path.join(apiRoot, "prisma/dev.db");
const migrationPaths = [
  path.join(apiRoot, "prisma/migrations/20260411103000_add_knowledge_workflow_v2/migration.sql"),
  path.join(apiRoot, "prisma/migrations/20260411124500_add_knowledge_operation_logs/migration.sql"),
  path.join(apiRoot, "prisma/migrations/20260411193000_add_hermes_skill_sync/migration.sql"),
  path.join(apiRoot, "prisma/migrations/20260411205000_add_mixed_project_mode/migration.sql")
];

const tempDir = mkdtempSync(path.join(os.tmpdir(), "occ-project-modes-completion-"));
const dbPath = path.join(tempDir, "test.db");

process.env.NODE_ENV = "test";
process.env.MODEL_PROVIDER = "scripted";
process.env.DATABASE_URL = `file:${dbPath}`;
process.env.PROJECT_WORKFLOW_V2_AUTO_INIT = "true";
process.env.PROJECT_WORKFLOW_V2_AUTO_START = "true";
process.env.PROJECT_WARMUP = "false";
process.env.ENFORCE_REAL_MODEL_GATE = "false";
process.env.WORKFLOW_V2_AGENT_AUTO_EXECUTE = "false";
process.env.WORKFLOW_V2_STAGE_AUTO_PROCEED = "false";
process.env.WORKFLOW_V2_FORCE_SCRIPTED_AGENT = "true";
process.env.WORKFLOW_V2_KNOWLEDGE_LLM_ENABLED = "false";

let prismaClient: any;
let createProjectFn: any;
let upsertTemplateFn: any;
let addStageOutputArtifactFn: any;
let transitionWorkflowStageFn: any;

const TEMPLATE_TO_ARTIFACT: Record<string, string> = {
  requirements_design: "prd",
  visual_design: "mockups",
  tech_design: "techSpec",
  code_dev: "sourceCode",
  qa_acceptance: "testReport"
};

function requiredArtifactForTemplate(templateKey: string) {
  return TEMPLATE_TO_ARTIFACT[templateKey] || `${templateKey}_output`;
}

async function upsertMinimalTemplate(input: {
  key: string;
  name: string;
  category: string;
  agentRole: string;
  requiredArtifact?: string;
}) {
  const requiredArtifact = input.requiredArtifact;
  await upsertTemplateFn({
    key: input.key,
    name: input.name,
    category: input.category,
    executorConfig: {
      type: "agent",
      agentRole: input.agentRole,
      requiredCapabilities: []
    },
    inputSchema: {},
    outputSchema: requiredArtifact ? { required: [requiredArtifact] } : {},
    acceptanceCriteria: requiredArtifact
      ? [{ type: "artifact_exists", config: { artifact: requiredArtifact, minLength: 16 } }]
      : [],
    integrationConfig: {},
    defaultTimeout: 120,
    allowParallel: false
  });
}

async function findWorkflowByProjectId(projectId: string) {
  return prismaClient.workflow.findFirst({
    where: { projectId },
    orderBy: { createdAt: "desc" },
    include: { stages: true }
  });
}

async function assertProjectCompleted(projectId: string, label: string) {
  const project = await prismaClient.project.findUnique({
    where: { id: projectId }
  });
  assert.ok(project, `${label}: project should exist`);
  assert.equal(project.status, "completed", `${label}: project status should be completed`);
  assert.equal(Number(project.progress), 100, `${label}: project progress should be 100`);
}

async function ensureArtifactAndProceed(input: {
  workflowId: string;
  stage: { id: string; templateKey: string; outputArtifacts: unknown };
}) {
  const artifactName = requiredArtifactForTemplate(input.stage.templateKey);
  const existingArtifacts = Array.isArray(input.stage.outputArtifacts)
    ? (input.stage.outputArtifacts as Array<Record<string, unknown>>)
    : [];
  const hasArtifact = existingArtifacts.some((item) => String(item.name || "") === artifactName);

  if (!hasArtifact) {
    await addStageOutputArtifactFn({
      stageId: input.stage.id,
      artifact: {
        name: artifactName,
        type: "markdown",
        content: `# ${artifactName}\n\nThis artifact is generated by project modes completion test.`,
        metadata: { source: "project_modes_completion_test" }
      }
    });
  }

  const transition = await transitionWorkflowStageFn({
    workflowId: input.workflowId,
    stageId: input.stage.id,
    action: "proceed",
    triggeredBy: "ROLE_PM",
    reason: "project modes completion test proceed"
  });
  assert.equal(transition.success, true, `stage transition failed for ${input.stage.templateKey}`);
}

async function completeWorkflow(workflowId: string) {
  for (let round = 0; round < 30; round += 1) {
    const workflow = await prismaClient.workflow.findUnique({
      where: { id: workflowId },
      include: { stages: true }
    });
    assert.ok(workflow, "workflow should exist");
    if (workflow.status === "completed") {
      return workflow;
    }

    const currentStageIds = Array.isArray(workflow.currentStageIds)
      ? (workflow.currentStageIds as string[])
      : [];
    assert.equal(currentStageIds.length > 0, true, "workflow should always have active currentStageIds before completion");

    for (const stageId of currentStageIds) {
      const stage = workflow.stages.find((item: { id: string }) => item.id === stageId);
      assert.ok(stage, `stage should exist for id=${stageId}`);
      await ensureArtifactAndProceed({
        workflowId,
        stage
      });
    }
  }

  throw new Error(`workflow ${workflowId} did not complete within iteration budget`);
}

before(async () => {
  snapshotSqliteSeedDatabase({
    seedDbPath,
    dbPath,
    cwd: apiRoot
  });
  for (const migrationPath of migrationPaths) {
    try {
      execSync(`sqlite3 ${JSON.stringify(dbPath)} < ${JSON.stringify(migrationPath)}`, {
        cwd: apiRoot,
        stdio: "pipe"
      });
    } catch {
      // Ignore idempotent replay errors when seed DB already contains newer schema columns.
    }
  }

  const [dbMod, repoMod, orchestratorMod] = await Promise.all([
    import("../db.js"),
    import("./repository.js"),
    import("../workflow-v2/workflow-orchestrator.js")
  ]);
  prismaClient = dbMod.prisma;
  createProjectFn = repoMod.createProject;
  upsertTemplateFn = orchestratorMod.upsertWorkflowTemplate;
  addStageOutputArtifactFn = orchestratorMod.addStageOutputArtifact;
  transitionWorkflowStageFn = orchestratorMod.transitionWorkflowStage;

  await upsertMinimalTemplate({
    key: "standard_software_development",
    name: "标准软件开发流程",
    category: "pm",
    agentRole: "Project_Manager"
  });
  await upsertMinimalTemplate({
    key: "requirements_design",
    name: "需求设计",
    category: "pm",
    agentRole: "Requirements_Analyst",
    requiredArtifact: "prd"
  });
  await upsertMinimalTemplate({
    key: "visual_design",
    name: "视觉设计",
    category: "design",
    agentRole: "UI_Designer",
    requiredArtifact: "mockups"
  });
  await upsertMinimalTemplate({
    key: "tech_design",
    name: "技术设计",
    category: "dev",
    agentRole: "Architect",
    requiredArtifact: "techSpec"
  });
  await upsertMinimalTemplate({
    key: "code_dev",
    name: "代码研发",
    category: "dev",
    agentRole: "Developer",
    requiredArtifact: "sourceCode"
  });
  await upsertMinimalTemplate({
    key: "qa_acceptance",
    name: "QA验收",
    category: "qa",
    agentRole: "QA_Engineer",
    requiredArtifact: "testReport"
  });
});

after(async () => {
  if (prismaClient) {
    await prismaClient.$disconnect();
  }
  rmSync(tempDir, { recursive: true, force: true });
});

test("single-stage projects: each template can reach 100% completion with deliverables", async () => {
  const standaloneTemplates = [
    "requirements_design",
    "visual_design",
    "tech_design",
    "code_dev",
    "qa_acceptance"
  ];

  for (const templateKey of standaloneTemplates) {
    const project = await createProjectFn(
      {
        name: `Standalone ${templateKey}`,
        description: `验证单阶段模板 ${templateKey} 可完整执行并交付`,
        projectType: "standalone",
        workflowTemplateKey: templateKey,
        autoStartWorkflow: true,
        projectInputs: [
          {
            name: "rawRequirements",
            type: "document",
            content: `Input for ${templateKey}.`
          }
        ]
      },
      "scripted"
    );

    const workflow = await findWorkflowByProjectId(project.id);
    assert.ok(workflow, `workflow should exist for standalone ${templateKey}`);
    const completed = await completeWorkflow(workflow.id);
    assert.equal(completed.status, "completed");

    const stage = completed.stages[0];
    assert.ok(stage, "standalone workflow should have one stage");
    const artifacts = Array.isArray(stage.outputArtifacts) ? stage.outputArtifacts : [];
    assert.equal(artifacts.length > 0, true, `standalone ${templateKey} should have output artifacts`);
    await assertProjectCompleted(project.id, `standalone ${templateKey}`);
  }
});

test("relay projects: different relay templates can reach 100% completion with deliverables", async () => {
  const sourceProject = await createProjectFn(
    {
      name: "Relay Source",
      description: "阶段接力来源项目",
      projectType: "complete",
      workflowTemplateKey: "standard_software_development",
      autoStartWorkflow: false
    },
    "scripted"
  );

  const sourceDeliverable = await prismaClient.deliverable.create({
    data: {
      projectId: sourceProject.id,
      stageType: "DESIGN",
      name: "source-design-deliverable",
      type: "markdown",
      content: "relay source deliverable content",
      version: 1,
      status: "approved",
      createdBy: "ROLE_DESIGN",
      updatedAt: new Date()
    }
  });
  assert.ok(sourceDeliverable.id);

  const relayTemplates = ["visual_design", "code_dev"];
  for (const templateKey of relayTemplates) {
    const relayProject = await createProjectFn(
      {
        name: `Relay ${templateKey}`,
        description: `验证阶段接力模板 ${templateKey} 完整执行`,
        projectType: "relay",
        parentProjectId: sourceProject.id,
        workflowTemplateKey: templateKey,
        autoStartWorkflow: true
      },
      "scripted"
    );

    const importedInputs = await prismaClient.projectInput.findMany({
      where: { projectId: relayProject.id }
    });
    assert.equal(importedInputs.length > 0, true, "relay project should import inputs from source deliverables");

    const workflow = await findWorkflowByProjectId(relayProject.id);
    assert.ok(workflow, `workflow should exist for relay ${templateKey}`);
    const completed = await completeWorkflow(workflow.id);
    assert.equal(completed.status, "completed");

    const stage = completed.stages[0];
    assert.ok(stage, "relay standalone workflow should have one stage");
    const artifacts = Array.isArray(stage.outputArtifacts) ? stage.outputArtifacts : [];
    assert.equal(artifacts.length > 0, true, `relay ${templateKey} should have output artifacts`);
    await assertProjectCompleted(relayProject.id, `relay ${templateKey}`);
  }
});

test("complete-flow project: can reach 100% completion with end-to-end deliverables", async () => {
  const project = await createProjectFn(
    {
      name: "Complete Flow Project",
      description: "验证完整流程项目可从需求到验收完整交付",
      projectType: "complete",
      workflowTemplateKey: "standard_software_development",
      autoStartWorkflow: true
    },
    "scripted"
  );

  const workflow = await findWorkflowByProjectId(project.id);
  assert.ok(workflow, "complete-flow project should have a workflow");

  const completed = await completeWorkflow(workflow.id);
  assert.equal(completed.status, "completed");
  assert.equal(completed.stages.length >= 5, true, "complete-flow should include at least 5 stages");

  for (const stage of completed.stages) {
    const artifacts = Array.isArray(stage.outputArtifacts) ? stage.outputArtifacts : [];
    assert.equal(
      artifacts.length > 0,
      true,
      `complete-flow stage ${stage.templateKey} should have deliverables`,
    );
  }
  await assertProjectCompleted(project.id, "complete-flow");
});
